#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="package.rest_elasticsearch"
export SOLECO_MODULE_VERSION=""
export SOLECO_HIDE_COMPONENT="true"
export MODECO_REST_ELASTICSEARCH_PREFIX="/${MODECO_URLPREFIX}/ekg/elasticsearch"
export MODECO_REST_ELASTICSEARCH_COMMAND="'.invoke test-api'"
##### END COMPONENT CONFIGURATION #####
