---
version: '3'
services:

# START SERVICE rest.elasticsearch
  rest:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.rest.elasticsearch:v1.0.2
    environment: ['CONTECO_STATIC_REST_BASE_API_LOGGING=${REST_ELASTICSEARCH_ENVIRONMENT_REST_BASE_CURL_LOGGING}','CONTECO_REST_BASE_PROTOCOL=${REST_ELASTICSEARCH_ENVIRONMENT_REST_ELASTICSEARCH_PROTOCOL}','CONTECO_REST_BASE_HOST=${REST_ELASTICSEARCH_ENVIRONMENT_REST_ELASTICSEARCH_HOST}','CONTECO_REST_BASE_PORT=${REST_ELASTICSEARCH_ENVIRONMENT_REST_ELASTICSEARCH_PORT}','CONTECO_REST_BASE_URLPREFIX=${REST_ELASTICSEARCH_ENVIRONMENT_REST_ELASTICSEARCH_PREFIX}']
    command: [${REST_ELASTICSEARCH_COMMAND}]
    volumes: ['${CONTECO_STACKPREFIX}_rest_elasticsearch_data_volume:/conteco/pwd'${REST_ELASTICSEARCH_VOLUMES_MAPPINGS}]
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${REST_ELASTICSEARCH_DEPLOY_MODE}
      resources:
        limits:
          memory: '${REST_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${REST_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      restart_policy: { condition: none }
${REST_ELASTICSEARCH_COMPOSE_EXTENSIONS}
# END SERVICE rest.elasticsearch

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_rest_elasticsearch_data_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
